### ISSUE TITLE
词云的数据是在哪里存储的呀，换了新的设备部署机器人之后就无法获得昨日词语之类的了

### ISSUE THREAD

**Issue by wjzlyr** [he0119/nonebot-plugin-wordcloud#114]

**Comment by he0119** [comment]
通过 `nb datastore dir` 命令可以看到。在数据目录下的 `data.db` 里。

**Comment by he0119** [comment]
那你试试 `nb localstore` 吧。可能是你的插件版本低的原因。

**Comment by wjzlyr** [comment]
> 那你试试 `nb localstore` 吧。可能是你的插件版本低的原因。

PS D:\Pydemo\Jbot> nb localstore
Usage: nb [OPTIONS] COMMAND [ARGS]...
Try 'nb --help' for help.

Error: No such command 'localstore'.
PS D:\Pydemo\Jbot> 
还是这样

**Comment by wjzlyr** [comment]
data.db具体是在哪个文件夹下呢，我去找找

**Comment by he0119** [comment]
<https://github.com/he0119/nonebot-plugin-datastore#datastore_data_dir>

**Comment by wjzlyr** [comment]
> https://github.com/he0119/nonebot-plugin-datastore#datastore_data_dir

谢谢大佬！
