### ISSUE TITLE
Feature: 命令比较多，我觉得可以加入帮助功能

### ISSUE THREAD

**Issue by wei-z-git** [he0119/nonebot-plugin-wordcloud#125]
我觉得可以加入帮助提示功能，以便用户参考

例如如下项目：
https://github.com/SK-415/HarukaBot/blob/efdf9da7f8ba733fac6f35461b23376d9f613c07/haruka_bot/plugins/help.py

**Comment by he0119** [comment]
但是现在已经是支持命令帮助的呀。适配的是 NoneBot 标准的 PluginMetadata。

https://github.com/he0119/nonebot-plugin-wordcloud/blob/13b432904ceccff24fbc119c55272a6f77176e04/nonebot_plugin_wordcloud/__init__.py#L49-L90
