### ISSUE TITLE
Bug: 默认词云形状不生效

### ISSUE THREAD

**Issue by LambdaYH** [he0119/nonebot-plugin-wordcloud#129]
### 描述问题

设置默认词云形状后，不起作用

### 如何复现

rt。

前面的`mask_key`好像无论如何都不为`None`，
https://github.com/he0119/nonebot-plugin-wordcloud/blob/45195f1b120e7869070a9ffb55a6a5e97269798a/nonebot_plugin_wordcloud/utils.py#L95-L104

那`get_mask_path`应该也就不会返回`plugin_data.data_dir / "mask.png" `
https://github.com/he0119/nonebot-plugin-wordcloud/blob/45195f1b120e7869070a9ffb55a6a5e97269798a/nonebot_plugin_wordcloud/config.py#L57-L61

### 期望的结果

没设置默认形状的群会使用默认词云形状

### 环境信息

- OS: [e.g. Linux]
- Python 版本: [e.g. 3.8]
- Nonebot 版本: [e.g. 2.0.0]
- 插件版本: [e.g. 1.0.0]

### 截图或日志

如果可以的话，请提供相关的截图或者日志。

**Comment by he0119** [comment]
确实，马上修（

**Comment by he0119** [comment]
合并了，试试主分支看看？如果没问题我就发给新版。

**Comment by LambdaYH** [comment]
> 合并了，试试主分支看看？如果没问题我就发给新版。

简单测试了一下，没问题了
