### ISSUE TITLE
”词云“命令容易误触发

### ISSUE THREAD

**Issue by MeetWq** [he0119/nonebot-plugin-wordcloud#18]
如果命令前缀设成空的话，所有”词云“开头的消息都会回复一大串帮助信息
要不要改成 to_me 才发送帮助？

**Comment by he0119** [comment]
哦哦，确实，识别成命令了。那我其实可以判断一下，有且仅有在输入 `词云` 这个词语的时候发送帮助信息？

**Comment by MeetWq** [comment]
好像也可以

**Comment by he0119** [comment]
那我就待会儿来改一下吧。

**Comment by he0119** [comment]
最新的 0.1.1 版本已经修改咯
