### ISSUE TITLE
包导入失败

### ISSUE THREAD

**Issue by 0xC4FED6C7CCCE** [he0119/nonebot-plugin-wordcloud#2]
__init__.py 下的 nonebot_plugin_datastore 导不进怎么回事啊？

**Comment by he0119** [comment]
应该是缺少依赖，你试试 `pip install nonebot-plugin-datastore`。

不过你是怎么安装呢？有日志么？

**Comment by 0xC4FED6C7CCCE** [comment]
> 应该是缺少依赖，你试试 `pip install nonebot-plugin-datastore`。
> 
> 不过你是怎么安装呢？有日志么？

**Comment by 0xC4FED6C7CCCE** [comment]
这个解决了  但是那个Zoneinfo是不是只有py3.9才能使用啊 
![C%PJP6}V`}R MJQ(1K Q%7H](https://user-images.githubusercontent.com/49481572/151752983-60901488-4554-45bc-932e-894172c9e043.png)

**Comment by he0119** [comment]
是啊，所以更低版本我依赖了 backports.zoneinfo。

你是直接复制的源代码么😂，你可以看看我 pyproject.toml 里写的依赖。

**Comment by 0xC4FED6C7CCCE** [comment]
啊这  感谢大佬的指导  菜哭了呜呜
