### ISSUE TITLE
能否屏蔽图片链接

### ISSUE THREAD

**Issue by Yonnemy2nd** [he0119/nonebot-plugin-wordcloud#21]
图片的链接和一些其他格式带的字符会被算入词云，希望能够仅捕捉或者显示文字消息的词云。

**Comment by he0119** [comment]
图片链接是指？我记得我只获得的纯文本来渲染词云的。

https://github.com/he0119/nonebot-plugin-wordcloud/blob/a0de754256c3cabfbe2d46527228611020b37720/nonebot_plugin_wordcloud/__init__.py#L207

而且也尝试去除了链接。

https://github.com/he0119/nonebot-plugin-wordcloud/blob/a0de754256c3cabfbe2d46527228611020b37720/nonebot_plugin_wordcloud/data_source.py#L16

能提供一下具体的数据么？

**Comment by he0119** [comment]
我自己测试发送图片加文字，数据库只会记录文字信息。

你能否在配置中加上 `datastore_database_echo=true`，然后重新测试，并发一下日志呢？

**Comment by Yonnemy2nd** [comment]
[CQ:image,file=141c5f4ac077c374261af7b01ff78360.image,url=https://gchat.qpic.cn/gchatpic_new/1648325438/2187033892-3179972961-141C5F4AC077C374261AF7B01FF78360/0?term=3,subType=1]"
2022-05-19 22:10:21,355 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-05-19 22:10:21,356 INFO sqlalchemy.engine.Engine INSERT INTO chatrecorder_message_record (platform, time, type, detail_type, message_id, message, alt_message, user_id, group_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2022-05-19 22:10:21,356 INFO sqlalchemy.engine.Engine [cached since 157.1s ago] ('qq', '2022-05-19 14:10:21.000000', 'message', 'group', '1869194140', '[{"type": "image", "data": {"file": "141c5f4ac077c374261af7b01ff78360.image", "url": "https://gchat.qpic.cn/gchatpic_new/1648325438/2187033892-3179972961-141C5F4AC077C374261AF7B01FF78360/0?term=3", "subType": "1"}}]', '',

主要信息是这样

**Comment by Yonnemy2nd** [comment]
看了下数据库，有一些信息的两端有 &#91;XXX&#93; 这样的格式，这种时候似乎不能辨别出一些信息，比如
{"text": "&#91;CQ:image,file=bb2f7f407fc325affb166e276aba8ba9.image,url=,type=flash,subType=0&#93;"}
没搞清楚是什么原因产生这样的格式

**Comment by he0119** [comment]
难道是你们在聊天过程中主动发送的文本？

**Comment by Yonnemy2nd** [comment]
我上面发的内容里的[]在数据库里都是 & #91 和 & #93

**Comment by Yonnemy2nd** [comment]
![image](https://user-images.githubusercontent.com/89773516/169326647-b69b92ea-4ffe-41ee-982c-54584150c72d.png)
像这样

**Comment by he0119** [comment]
> ![image](https://user-images.githubusercontent.com/89773516/169326647-b69b92ea-4ffe-41ee-982c-54584150c72d.png) 像这样

这种就是你主动发送了 `[CQ:image,file=bb2f7f407fc325affb166e276aba8ba9.image,url=,type=flash,subType=0]` 这段文字。type=text 就是文本格式的意思。`&#91` 我确实不太明白是什么，我待会儿查查看。

**Comment by Yonnemy2nd** [comment]
这俩是[]的ASCII码值，问题应该出在记录的插件上，可能是chatrecorder的问题？也许应该去那边投个issue

**Comment by MeetWq** [comment]
我有个猜想，应该是商店表情
nonebot 接收到的商店表情是纯文本带括号的形式，比如 `[开心]`
然后 `[` 和 `]` 被 `escape`，就会有很多 `&#91` 和 `&#93`

**Comment by Yonnemy2nd** [comment]
> 

有的。我测试一下商店表情。

**Comment by he0119** [comment]
> 我有个猜想，应该是商店表情 nonebot 接收到的商店表情是纯文本带括号的形式，比如 `[开心]` 然后 `[` 和 `]` 被 `escape`，就会有很多 `&#91` 和 `&#93`

我试了一下，`'[{"type": "text", "data": {"text": "[看手机]"}}]', '[看手机]'`，还挺正常的。

**Comment by Yonnemy2nd** [comment]
> > 我有个猜想，应该是商店表情 nonebot 接收到的商店表情是纯文本带括号的形式，比如 `[开心]` 然后 `[` 和 `]` 被 `escape`，就会有很多 `&#91` 和 `&#93`
> 
> 我试了一下，`'[{"type": "text", "data": {"text": "[看手机]"}}]', '[看手机]'`，还挺正常的。

表情应该影响了 &#，91，93 这几个字符，但是带图片信息的我没能复现，不确定是什么原因。

**Comment by Yonnemy2nd** [comment]
> 直接打开数据库看看 `CQ:image` 这样的多不多？

不算多，看了下之前的很少有，只有最近几天密度稍高。

**Comment by he0119** [comment]
你现在能不能复现呢？如果可能的话提供一下步骤吧。不然太迷惑了，我这边也不知道怎么回事。

**Comment by Yonnemy2nd** [comment]
没搞清楚。这种信息占比不大。主要问题是中括号显示成 ascii 码，其他符号没有这种现象，可能是我自己的一些问题。先关闭这个 issue 了。

**Comment by he0119** [comment]
> 没搞清楚。这种信息占比不大。主要问题是中括号显示成 ascii 码，其他符号没有这种现象，可能是我自己的一些问题。先关闭这个 issue 了。

那等可以复现了，记得告诉我一下。我也挺好奇的。
