### ISSUE TITLE
关于 numpy 的依赖

### ISSUE THREAD

**Issue by MeetWq** [he0119/nonebot-plugin-wordcloud#22]
似乎并没有直接用到 `numpy` 的地方
和另一个插件冲突了（x

**Comment by he0119** [comment]
有道理，我当时因为 CI 跑不过加的，其实不应该把 `poetry.lock` 传上来的。

稍等，我改改。

**Comment by he0119** [comment]
https://github.com/he0119/nonebot-plugin-wordcloud/releases/tag/v0.1.2

这样应该就可以了，你试试？
