### ISSUE TITLE
Bug: 0.5.1插件加载报错，可能和alconna版本有关

### ISSUE THREAD

**Issue by wei-z-git** [he0119/nonebot-plugin-wordcloud#250]
### wordcloud 版本

0.5.1

### chatrecorder 版本

0.4.2

### saa 版本

0.3.0

### alconna 版本

nonebot-plugin-alconna                0.29.0

### 描述问题

新环境未指定alconna版本时直接启动加载词云会报错
![94816342911d40562f3e440fd1ec75b1](https://github.com/he0119/nonebot-plugin-wordcloud/assets/32572815/013c23f9-cc0b-4385-9632-d33fb14891e1)

指定版本后就能加载了
nonebot-plugin-alconna==0.19.2

最新版词云也会报错

### 复现步骤

如上

**Comment by he0119** [comment]
应该在最新的版本中修复了。
