### ISSUE TITLE
wordcloud导入出错（似乎与alconna与orm有关）

### ISSUE THREAD

**Issue by TheValkyrja** [he0119/nonebot-plugin-wordcloud#260]
### wordcloud 版本

0.7.0

### chatrecorder 版本

0.6.0

### saa 版本

0.6.0

### alconna 版本

0.38.2

### 描述问题

使用nb-cli运行bot操作时无法正确导入wordcloud。

### 复现步骤

1.nb plugin install nonebot_plugin_wordcloud。
2.bot目录下直接执行nb run（wordcloud导入失败，orm提示需要更新，启动检查失败并退出。）
3.同目录下执行nb orm upgrade（wordcloud导入失败并退出，orm正常加载。）

上述两个行为中，wordcloud均提示：

>  File "<string>", line 14, in __init__
> TypeError: MessageArgv.__post_init__() takes 1 positional argument but 2 were given

### 期望的结果

正常导入/更新两项插件并启动bot服务

### 截图或日志

步骤2当中的两段报错：
![image](https://github.com/he0119/nonebot-plugin-wordcloud/assets/45366459/bb8c42af-9430-4a40-a328-37b597a78ad5)
![image](https://github.com/he0119/nonebot-plugin-wordcloud/assets/45366459/7be053c9-c7d4-4871-8547-a2e672d26192)

步骤3当中的两段报错：
![image](https://github.com/he0119/nonebot-plugin-wordcloud/assets/45366459/8e10c847-9c62-496b-9456-3cca2efedc19)
![image](https://github.com/he0119/nonebot-plugin-wordcloud/assets/45366459/9c8cdbb6-7aae-4527-abcb-479dd8a69b95)

**Comment by he0119** [comment]
是的，这个是 alc 的问题，请降级 arclet-alconna 包至 1.8.3 版本。

**Comment by TheValkyrja** [comment]
> arclet-alconna

感谢，执行pip install arclet-alconna==1.8.3后问题解决。
