### ISSUE TITLE
Bug: 多个群设置同一时间发送今日词云，会因为有一个群被封造成所有没法正常发送

### ISSUE THREAD

**Issue by chenyue314** [he0119/nonebot-plugin-wordcloud#281]
### wordcloud 版本

——

### chatrecorder 版本

——

### saa 版本

——

### alconna 版本

——

### 描述问题

这几天观测到，多个群设置同一时间发送今日词云，会因为有一个群被封造成所有没法正常发送，会因为被封的群今天没有聊天记录，造成没法发送，并且影响其他群。

### 复现步骤

删除没被封的群的自动发送，错开时间重新设置，就可以正常发送。

### 期望的结果

希望可以增加删除指定群号的自动发送功能，因为群被封了，也没法在被封群发送命令去关闭词云每日定时发送

**Comment by he0119** [comment]
这确实，看来还需要做一个群管理功能。做成超级用户私聊修改怎么样？

**Comment by chenyue314** [comment]
好

**Comment by he0119** [comment]
准备先把发送失败导致其他群组无法发送的问题修了，然后再来实现群管理功能。
