### ISSUE TITLE
大佬能否加个每日定时发送今日的词云。

### ISSUE THREAD

**Issue by SakuraXiaoWen** [he0119/nonebot-plugin-wordcloud#31]

**Comment by he0119** [comment]
应该可以。

**Comment by he0119** [comment]
> 好像用 nonebot_plugin_apscheduler 能实现

是的，不过我还没想好怎么配置比较舒服。

**Comment by he0119** [comment]
是直接通过配置项来配置好，还是增加一个新的命令配置更好呢？需要每个群单独控制定时发送的时间吗？

**Comment by he0119** [comment]
想想可能有人同时连接好几个机器人。看来还是用命令多获取点信息，直接一步到位好了。
