### ISSUE TITLE
怎么修改词云里文字的颜色呀

### ISSUE THREAD

**Issue by huihuiismywife** [he0119/nonebot-plugin-wordcloud#33]
如题，看着配色感觉有点不舒服，想换个颜色的文字

**Comment by he0119** [comment]
有点麻烦，现在文字颜色都是自动生成的，只能修改背景颜色。

如果你想修改的话，可以自己修改源代码，传入 `color_func` 或者 `colormap` 参数。

https://github.com/he0119/nonebot-plugin-wordcloud/blob/c0f6ae35fc22c2444e04b6a86b20fb97b32b0d7f/nonebot_plugin_wordcloud/data_source.py#L54-L59

文档参考：<https://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud>

**Comment by huihuiismywife** [comment]
好吧，谢谢大佬，我这边学着看看吧 _(:з」∠)_

**Comment by he0119** [comment]
也许我可以把 `colormap` 作为配置项。这样至少可以用上 `Matplotlib` 自带的 [colormap](https://matplotlib.org/3.5.0/tutorials/colors/colormaps.html)。
