### ISSUE TITLE
怎么实现自定义的图效果呢

### ISSUE THREAD

**Issue by liuzj288** [he0119/nonebot-plugin-wordcloud#35]
两个问题，
第一个，现在参数只能更换颜色呢，自定义怎么修改，比如下面这样的
第二个，jieba分词怎么设置模式？jieba 分词有 3 种方式：精确模式、全模式和搜索引擎模式，应该选择「精确模式」来分词吧
![image](https://user-images.githubusercontent.com/13833404/173055234-0a52c664-5b15-4c0f-b284-4fb54bb70b24.png)

**Comment by he0119** [comment]
1. 现在插件做不到自定义图片形状，如果你想自己修改的话，可以参考 <https://amueller.github.io/word_cloud/auto_examples/masked.html#sphx-glr-auto-examples-masked-py> 自己修改源代码。我还没想好该怎么在插件中实现。
2. 现在是直接使用 <https://github.com/he0119/nonebot-plugin-wordcloud/pull/25> 获取词频，没法设置分词模式。

**Comment by liuzj288** [comment]
zhenxun那个群词云的效果怎么实现的呢，感觉是魔改了啥还没研究明白

![~0Y{@JKUSP77C$RCX1)BSQ0](https://user-images.githubusercontent.com/13833404/177257869-0cdf6784-c11c-4c27-8a4b-e4fca6e3b432.PNG)

**Comment by he0119** [comment]
其实就是我之前说的，加了一个 mask。我计划这周也给这个词云添加设置形状的功能。
