### ISSUE TITLE
__init__文件186行 messages = await get_message_records 返回空值

### ISSUE THREAD

**Issue by ztreble** [he0119/nonebot-plugin-wordcloud#48]
数据库文件路径如下：
![4C3_SC6HO`31ZJM%2EBZS%Y](https://user-images.githubusercontent.com/44469959/177674301-7e43b5a8-9102-4667-84a6-c745181c9304.png)

**Comment by he0119** [comment]
你的意思是没有记录到聊天记录么？

**Comment by ztreble** [comment]
![TYLN0FQR6Q10ZLPRX(36_4](https://user-images.githubusercontent.com/44469959/177676178-ba140807-7bb2-4afd-aa28-85703f328903.png)
nonebot-plugin-datastore这个插件存放路径是data.db，这个文件打不开
![image](https://user-images.githubusercontent.com/44469959/177676834-10e9026e-214c-497c-a438-0f205fac1f84.png)
不清楚是nonebot_plugin_chatrecorder存放还是读取出问题了

**Comment by he0119** [comment]
看起来是数据库文件出问题了，你删除重新建立一下试试呢？

**Comment by ztreble** [comment]
不行呢

**Comment by he0119** [comment]
那你把 nb 的日志等级调整成 debug 吧，然后发一下日志。

**Comment by ztreble** [comment]
还是会出现这个问题。
session commit之前都是没有问题的，消息也能log出来

**Comment by ztreble** [comment]
[wordcloud.log](https://github.com/he0119/nonebot-plugin-wordcloud/files/9060022/wordcloud.log)

我在chatrecorder里面加了两个log，也都不报错
![(B~ C8 %Z_5BPGZVD0)%6EI](https://user-images.githubusercontent.com/44469959/177681520-e3bd5886-f30a-4b69-9fbf-4177b059489e.png)

**Comment by ztreble** [comment]
最后有个warning
SAWarning: Class SelectOfScalar will not make use of SQL compilation caching as it does not set the 'inherit_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this object can make use of the cache key generated by the superclass.  Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  results = super().execute(

**Comment by he0119** [comment]
奇怪，聊天记录确实都正确记录了。（warning 无所谓啦，不是 error 就好

你试试 `/历史词云 2022-01-01~2022-12-31` 呢？我也许知道问题所在了。

**Comment by ztreble** [comment]
可以正常生成

**Comment by he0119** [comment]
果然，这个是 nonebot_plugin_chatrecorder 的问题。它在保存时间数据的时候，没有确保存成 UTC 时间，导致有 8 个小时的时间差。所以你刚发送的消息，要过 8 小时候之后才能出现。

**Comment by ztreble** [comment]
那咋修复啊

**Comment by he0119** [comment]
稍微等等 MeetWq 发布 nonebot_plugin_chatrecorder 新版本，然后我也会发布一个新的版本，提高依赖限制。之后你升级就好了。你着急的话，可以把 <https://github.com/noneplugin/nonebot-plugin-chatrecorder/blob/0e041359b3a3bdad16dab927dabfe49d0116cc73/nonebot_plugin_chatrecorder/model.py#L14> 改成 `utcfromtimestamp`。

**Comment by ztreble** [comment]
好的，感谢作者大大

**Comment by he0119** [comment]
`0.2.4` 已经发版，这个问题应该修复了。
