### ISSUE TITLE
在python3.11中安装会报错

### ISSUE THREAD

**Issue by balh55y** [he0119/nonebot-plugin-wordcloud#73]
![~@Q(~~ER~RVZ3E__9_8A%3B](https://user-images.githubusercontent.com/85926883/201836354-ee5ca070-254f-45d0-8560-d8cb4d37eaa5.png)
![UCO4%D6QX{I~7QJVQ`)9W0](https://user-images.githubusercontent.com/85926883/201836366-9a5c2d0a-028b-4330-bfd6-7549d084bf2d.png)

貌似是没有longintrepr.h了?

**Comment by he0119** [comment]
这个只能等 word_cloud 更新。 https://github.com/amueller/word_cloud/issues/691
