### ISSUE TITLE
屏蔽CQ码

### ISSUE THREAD

**Issue by lancer-wang** [he0119/nonebot-plugin-wordcloud#74]
在data_source.py 去除网址前面一行加上
msg = re.sub(r"\[CQ:.*\]", "", msg) 就行了

**Comment by lancer-wang** [comment]
如果先去除网址，似乎会把cq码后面的] 给去掉从而匹配不到

**Comment by he0119** [comment]
https://github.com/noneplugin/nonebot-plugin-chatrecorder/blob/6a6a25c1cf24869b4621a1987688fd79af6e12a9/nonebot_plugin_chatrecorder/__init__.py#L28

我记得聊天记录保存的是纯文本呀，为什么会有CQ码？

**Comment by lancer-wang** [comment]
好吧，我用的和你不是一个数据库，我的是有存CQ码的
