### ISSUE TITLE
发送/今日词云 没有响应，nonebot-plugin-chatrecorder和nonebot-plugin-datastore都安装了

### ISSUE THREAD

**Issue by 2018PAN** [he0119/nonebot-plugin-wordcloud#84]

**Comment by 2018PAN** [comment]
是必须要配置env文件吗

**Comment by he0119** [comment]
有任何报错吗？按理来说如果不是需要特定配置是不需要配置，都有默认配置的。

**Comment by 2018PAN** [comment]
> 有任何报错吗？按理来说如果不是需要特定配置是不需要配置，都有默认配置的。

没有报错，就是单纯的不响应词云插件。我只用nb install安装了那两个插件，本地的cache文件也是存在的

**Comment by he0119** [comment]
可以开一下debug模式，然后把log发上来吗？我想看看是为什么没有匹配到。

**Comment by 2018PAN** [comment]
> 可以开一下debug模式，然后把log发上来吗？我想看看是为什么没有匹配到。

不好意思，不太会调用log😥

**Comment by 2018PAN** [comment]
> 可以开一下debug模式，然后把log发上来吗？我想看看是为什么没有匹配到。
error.log一直是空的

**Comment by he0119** [comment]
你可以在配置项里加上 `LOG_LEVEL=DEBUG`，然后把你启动 nb 的那个界面里的内容复制上来。

**Comment by 2018PAN** [comment]
![image](https://user-images.githubusercontent.com/41419312/211245585-d8241e1f-42c7-4cee-8b44-695694c99b43.png)

**Comment by he0119** [comment]
奇怪，完全没有触发词云的 matcher。你 `COMMAND_START` 的配置是什么？

**Comment by 2018PAN** [comment]
COMMAND_START=["","/"]，我试过只有“/”的情况，也不能触发。.toml文件里写的是plugins = ["nonebot_plugin_chatrecorder", "nonebot_plugin_datastore"]，不知道为啥触发不了

**Comment by he0119** [comment]
> COMMAND_START=["","/"]，我试过只有“/”的情况，也不能触发。.toml文件里写的是plugins = ["nonebot_plugin_chatrecorder", "nonebot_plugin_datastore"]，不知道为啥触发不了

草，你怎么不把最重要的 nonebot_plugin_wordcloud 加上，其实那两个不写也没事。

**Comment by 2018PAN** [comment]
> > COMMAND_START=["","/"]，我试过只有“/”的情况，也不能触发。.toml文件里写的是plugins = ["nonebot_plugin_chatrecorder", "nonebot_plugin_datastore"]，不知道为啥触发不了
> 
> 草，你怎么不把最重要的 nonebot_plugin_wordcloud 加上，其实那两个不写也没事。

我超，忘了，给大佬添麻烦了，我现在就去装

**Comment by 2018PAN** [comment]
可以正常运行了，如果要清理聊天记录数据就只需要删除data.db吗

**Comment by he0119** [comment]
不是很建议删除 `data.db`，因为词云定时发送相关的配置也是保存在里面的。你可以用 [DB Browser for SQLite](https://sqlitebrowser.org/) 或类似软件，删除数据库内的 chatrecorder 表。

**Comment by 2018PAN** [comment]
好的好的，非常感谢
