### ISSUE TITLE
更新之后报错了，缺少 OneBot 12 相关模块

### ISSUE THREAD

**Issue by liuzj288** [he0119/nonebot-plugin-wordcloud#94]
![image](https://user-images.githubusercontent.com/13833404/214072253-60de00a2-4fc4-4b8f-b32c-8b70478aeb41.png)

**Comment by he0119** [comment]
支持的，奇怪了，OneBot 11与12是在一个包呀。为什么你没有v12的？

**Comment by he0119** [comment]
啊这，原来是 [2.1.0](https://github.com/nonebot/adapter-onebot/releases/tag/v2.1.0) 版本才加的。我马上改一下依赖。

**Comment by liuzj288** [comment]
还没完全解决
![image](https://user-images.githubusercontent.com/13833404/214127878-ccfefa41-62b1-4295-a275-ddb26cc9d3d6.png)

**Comment by he0119** [comment]
那我不清楚了…

**Comment by he0119** [comment]
> 还没完全解决，也有可能是py插件因素 ![image](https://user-images.githubusercontent.com/13833404/214127878-ccfefa41-62b1-4295-a275-ddb26cc9d3d6.png)

根据群友的说法，是 py-plugin 的问题，建议向那个插件提 issue。

>【潜水】Forever? 8:28:29
>py-plugin patch了onebot adapter
>
>【潜水】Forever? 8:28:33
>只有ob11

**Comment by liuzj288** [comment]
> py-plugin 的问题，建议向那个插件提 issue。

git pull之后怎么回退版本呢
