### ISSUE TITLE
Python 3.11 安装 wordcloud 失败

### ISSUE THREAD

**Issue by rickly233** [he0119/nonebot-plugin-wordcloud#97]
安装失败
报错如下:
![image](https://user-images.githubusercontent.com/92252768/215103790-9c0272d9-cf0c-4519-bd3a-5308616170b1.png)

![image](https://user-images.githubusercontent.com/92252768/215103877-2ea8ab4d-52b4-48fd-86f6-1f53ade1cf21.png)

**Comment by he0119** [comment]
[wordcloud](https://pypi.org/project/wordcloud/#files) 在 Python 3.11 上没有带 wheel，你需要自己安装编译环境来安装。

**Comment by he0119** [comment]
最近 wordcloud 发布新版 1.9.2，支持 Python 3.11 了。
